-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJBLsDcVTEn90HAr8
g7KiWiNxnt0AkFNTlx+3lsqX1zKgCgYIKoZIzj0DAQehRANCAASgSzGu+5maCwga
nw0xan9QH60cxw5iTRtipeQmjAyDb2OamanCn6TaSdUk1bq7iB1YElt7hegrTmtC
cBuaOWJg
-----END PRIVATE KEY-----